### ISSUE TITLE
Icons broken with Solid v1.8.0

### ISSUE THREAD

**Issue by caseybaggz** [x64Bits/solid-icons#55]
After upgrading I'm seeing massive issues with the icon rendering that returns empty `svg` tags with no content. If you remove the code then save, they appear - but break again when the page refreshes.

All the blank spots should be using Github Icons.

<img width="419" alt="Screenshot 2023-10-10 at 8 18 26 AM" src="https://github.com/x64Bits/solid-icons/assets/4819738/f075dda8-1d55-435e-a6fb-2a6df42e3244">

**Comment by rpivo** [comment]
If you upgrade to solid-js@1.8.1, the icons may work, but there will be a warning in the console.

**Comment by caseybaggz** [comment]
@rpivo will this be fixed on the solid-icons side in the near future? Knowing that the library is not exporting properly, having warning logs all over my app is a non-negotiable and if not remedied soon will force me to have to refactor to another icon library or manage my own which I prefer not to do. 😢

**Comment by caseybaggz** [comment]
Still broken unfortunately, however, the beta candidate does fix this issue!

**Comment by rpivo** [comment]
Yeah, seeing the same issues on my end as well 😕

I can't speak for the maintainers of this library, but sounds like the build it exports needs to be hydratable based on discussion in Solid's discord.

Others there have recommended trying unocss + the unocss icons plugin in place of solid-icons in the event that this isn't fixed soon. I am migrating from vanilla css and solid-icons to unocss + icons plugin based on hearing that someone else in the discord also made the same switch.

https://unocss.dev/guide/
https://unocss.dev/presets/icons
https://icones.js.org/collection/all

**Comment by rpivo** [comment]
Yeah, 😕 luckily I only had six or so files to migrate, and even then I didn't want to spend my time like this. Maybe solid-icons will make an update here.

**Comment by x64Bits** [comment]
Hello everyone, thank you for reporting this, did you check if, as mentioned above, is this resolved in the beta version? I have not been able to launch because I plan to include in the next version a solution for the problem that was happening when creating a build with astro, I will try to release a version sooner to solve this problem since 1.8.

**Comment by xNoobyyy** [comment]
> Still broken unfortunately, however, the beta candidate does fix this issue in the UI with the caveat of still having the hydration error which should probably be fixed in that release:
> 
> ```shell
> Error: Failed attempt to create new DOM elements during hydration. Check that the libraries you are using support hydration.
>     at create (dev.js:571:13)
>     at dev.js:579:63
>     at untrack (dev.js:495:33)
>     at Function.cloneNode (dev.js:579:13)
>     at index.js:11:25
>     at IconTemplate (index.js:50:3)
>     at OcStack2 (index.js:2961:14)
>     at dev.js:616:16
>     at untrack (dev.js:499:12)
>     at Object.fn (dev.js:612:7)
> ```
> 
> **EDIT** Looks like the Beta version is still broken failing both our unit tests and deploy-previews (due to hydration issues and missing content).

this is still happening to me in the beta version as already mentioned

**Comment by x64Bits** [comment]
I have sent a new [beta version (1.1.0-beta.2)](https://www.npmjs.com/package/solid-icons/v/1.1.0-beta.2) that solves this problem in version 1.8 of solid-js, I have changed the import strategy avoiding importing a precompiled (Ryan suggested this on discord), with these changes the astro and cloudflare compilation now works correctly, please if anyone can test this version in their projects to send it in a stable version as soon as possible, greetings.

**Comment by outbackStack** [comment]
`1.1.0-beta.2` now works with Astro. Thanks @x64Bits

**Comment by outbackStack** [comment]
Thanks @x64Bits. `1.1.0-beta.2` works for a normal icon now using Astro.

But when it's under a modal, I'm getting these errors bellow when the `Show` control is true.

<img width="1034" alt="Screenshot 2023-10-14 at 12 16 31 pm" src="https://github.com/x64Bits/solid-icons/assets/16639496/e905547c-166a-4c36-a23a-c30ef9a88900">
<img width="518" alt="Screenshot 2023-10-14 at 12 20 07 pm" src="https://github.com/x64Bits/solid-icons/assets/16639496/47d620a6-53f7-4fa9-89c9-a101701d2f87">

**Comment by greg-hammond** [comment]
Installing 1.1.0-beta.2 fixed the initial icon problem I was seeing, but actually started crashing other pages that use solid-icon. 

`"Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."`

IDK if this error message strictly belongs to `solid-js` or `solid-icon`, but I was forced to roll back the change.  I guess a few missing icons is better than failing pages in prod...

@x64Bits is this actively being worked on with ryan and crew?

**Comment by xNoobyyy** [comment]
> Installing 1.1.0-beta.2 fixed the initial icon problem I was seeing, but actually started crashing other pages that use `solid-icons`.
> 
> `"Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."`
> 
> IDK if this error message strictly belongs to `solid-js` or `solid-icons`, but I was forced to roll back the change. I guess a few missing icons is better than failing pages in prod...
> 
> @x64Bits is this actively being worked on with ryan and crew?

can confirm, cant use the library atm :/

**Comment by x64Bits** [comment]
Sorry for the delay in responding, I had difficulties attending to the project these last two weeks, but I am already addressing this problem again, this other issue reported something similar related to hydration #56, I would like to find out if it is the same problem, could someone help me? Is it happening to you to create a small sandbox using solid-icons@1.1.0-beta.2?

Regarding whether I'm working with the solid team, I am always very attentive to the community but I don't interact much, luckily Ryan explained about this in the SSR channel on discord, when i asked.

**Comment by x64Bits** [comment]
The latest issue #56 @elijah629 helped me reproduce the error, I'm submitting changes in the latest beta.3 version, it seems to me that once I verify that these changes work well, I can release 1.1.0

**Comment by x64Bits** [comment]
As with #56, I'll assume it's been resolved since the last update, thank you very much for all the feedback!
